version = 0.1

[default]
[default.global.parameters]
stack_name = "receipt-ocr-api"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "receipt-ocr-api"
region = "ap-northeast-1"
image_repositories = ["ReceiptOCRFunction=116981786149.dkr.ecr.ap-northeast-1.amazonaws.com/receiptocrapi3d3a6aa7/receiptocrfunction76d76e4brepo"]
disable_rollback = true
parameter_overrides = "Stage=\"dev\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Staging環境設定
[staging]
[staging.global.parameters]
stack_name = "receipt-ocr-api-staging"

[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "receipt-ocr-api-staging"
region = "ap-northeast-1"
image_repositories = ["ReceiptOCRFunction=116981786149.dkr.ecr.ap-northeast-1.amazonaws.com/receiptocrapi3d3a6aa7/receiptocrfunction76d76e4brepo"]
disable_rollback = true
parameter_overrides = "Stage=\"staging\""

# Production環境設定
[production]
[production.global.parameters]
stack_name = "receipt-ocr-api-production"

[production.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "receipt-ocr-api-production"
region = "ap-northeast-1"
image_repositories = ["ReceiptOCRFunction=116981786149.dkr.ecr.ap-northeast-1.amazonaws.com/receiptocrapi3d3a6aa7/receiptocrfunction76d76e4brepo"]
disable_rollback = true
parameter_overrides = "Stage=\"production\"" 