service: ocr-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  timeout: 30
  memorySize: 1024
  
  environment:
    ENVIRONMENT: ${self:provider.stage}
    API_TOKEN: ${env:API_TOKEN, 'demo-token-12345'}
    LOG_BUCKET: ${env:LOG_BUCKET, ''}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: 
        - "arn:aws:s3:::${env:LOG_BUCKET, 'ocr-logs'}/*"

functions:
  ocr:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true
    layers:
      - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p39-Pillow:15
      # Tesseract layer (要作成)
      # - arn:aws:lambda:ap-northeast-1:xxxxx:layer:tesseract:1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    strip: false
    pipCmdExtraArgs:
      - --no-cache-dir 