AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  レシートOCR API
  
  FastAPIベースのレシートOCRサービス

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type,authorization'"
      AllowOrigin: "'*'"
    BinaryMediaTypes:
      - image/*
      - application/octet-stream

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: デプロイメント環境

Resources:
  ReceiptOCRFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "receipt-ocr-api-${Stage}"
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          STAGE: !Ref Stage
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiGatewayRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.13-v1

Outputs:
  ApiGateway:
    Description: "Receipt OCR API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
  ReceiptOCRFunction:
    Description: "Receipt OCR Lambda Function ARN"
    Value: !GetAtt ReceiptOCRFunction.Arn
  ReceiptOCRFunctionIamRole:
    Description: "Implicit IAM Role created for Receipt OCR function"
    Value: !GetAtt ReceiptOCRFunctionRole.Arn 